name: 'http-continuous-benchmarking'
author: 'tomoyane'
description: 'This GitHub Actions provides a http continuous benchmarking'
inputs:
  # Http request
  target_url:
    description: 'Request target url. Start http(s)://xxxxx.'
    required: true
  http_headers:
    description: 'Request HTTP Headers. {} format.'
    required: true
    default: '{"Content-Type": "application/json"}'
  thread_num:
    description: 'Benchmark thread num.'
    required: true
    default: '1'
  trial_num:
    description: 'Benchmark trial number while 5seconds. If its 5times, the benchmark try 5times * 5seconds. Ex: Case of API 100rps, 100(rps) * 5(seconds) * 5(times)'
    required: true
    default: '1'
  req_http_method_ratio:
    description: 'Request HTTP Methods ratio. {} format.'
    required: true
    default: '{"GET": 10}'
  req_body:
    description: 'HTTP Request Body. {} format. If you use PUT or PATCH or POST, its required.'
    required: false

  # Alert notification
  enable_alert:
    description: 'Alert. You want to catch alert when over threshold.'
    required: false
    default: 'false'
  slack_web_hook_url:
    description: 'Slack web hook url.'
    required: false
  slack_channel:
    description: 'Slack channel.'
    required: false
  slack_notify_threshold_latency_millis:
    description: 'Threshold latency milliseconds for notification. This is to check latency average'
    required: false
  slack_notify_threshold_rps:
    description: 'Threshold request per seconds for notification.'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'bar-chart-2'  
  color: 'white'
